spring:
  application:
    name: gateway-server
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 003-Microservice-extraction
