spring:
  jackson:
    default-property-inclusion: always
  boot:
    admin:
      client:
        url: http://localhost:8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
