spring:
  boot:
    admin:
      client:
        url: http://admin-server:8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
opentracing:
  jaeger:
    udp-server:
      host: jaeger-server
      port: 6831
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  auth-server-url: http://keycloak-server:8080
