server:
  port: 10003
spring:
  cloud:
    function:
      definition: ordersEvents
    stream:
      bindings:
        ordersEvents-in-0:
          destination: orders-events
          group: reporter
