server:
  port: 10000
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/payments.db
    username: admin
    password: admin
logging:
  level:
    pl.training: DEBUG
feign:
  client:
    config:
      default:
        logger-level: BASIC
api:
  products: http://WAREHOUSE-SERVICE/products/
