spring:
  application:
    name: shop-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 009-Resilience4j
encrypt:
  key: YWMMEHRICKEU
