version: '3'
services:
  zookeeper-server:
    image: wurstmeister/zookeeper
    restart: always
  kafka-server:
    image: wurstmeister/kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
  admin-server:
    image: training/admin-server
    restart: always
    environment:
      PORT: 8090
    ports:
      - "8090:8090"
  configuration-server:
    image: training/configuration-server
    restart: always
    environment:
      #SERVER_PORT: 8888
      PORT: 8888
      GIT_URI: https://github.com/landrzejewski/spring-cloud-training
      KAFKA_BROKERS: kafka-server
      ENCRYPT_KEY: YWMMEHRICKEU
    # ports:
    #  - "8888:8888"
  discovery-server:
    image: training/discovery-server
    restart: always
    environment:
      PROFILE: production
      CONFIGURATION_SERVER: optional:configserver:http://configuration-server:8888
    ports:
      - "8761:8761"
  gateway-server:
    image: training/gateway-server
    restart: always
    environment:
      PROFILE: production
      CONFIGURATION_SERVER: optional:configserver:http://configuration-server:8888
    ports:
      - "8080:8080"











