spring:
  application:
    name: payments-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 004-Kafka-communication
