spring:
  application:
    name: reporting-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 007-Monitoring-tracing-and-logs
