spring:
  application:
    name: warehouse-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 002-Http-communication
