spring:
  application:
    name: broker-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 006-Reactive-services
